const contentArray = [
  {
    urlStub: '/reports',
    pageHeading: 'Reports Dashboard',
    pageBlurb: null,
    formIntroHeading: null,
    formIntroBlurb: null,
    buttonText: 'Start now',
    buttonLink: 'save-voyage/page-1',
    buttonClass: 'govuk-button--start',
    buttonLocation: 'intro',
    reportType: 'tabs',
  },
  {
    urlStub: '/vessels',
    pageHeading: 'Vessels',
    pageBlurb: 'You can view, edit or delete vessels that you regularly add to Pleasure Craft Reports.',
    formIntroHeading: 'Save a new vessel',
    formIntroBlurb: 'Save the details of vessels that you regularly submit Pleasure Craft Reports for.',
    buttonText: 'Save a vessel',
    buttonLink: 'vessels/save-vessel?source=vessels',
    buttonClass: 'govuk-button--start',
    buttonLocation: 'formIntro',
    reportType: 'vessels',
    reportTitles: ['Vessel name', 'Vessel type', 'Usual moorings'],
  },
  {
    urlStub: '/people',
    pageHeading: 'People',
    pageBlurb: 'You can view, edit or delete people that you regularly sail with so that you can easily add them to Pleasure Craft Reports.',
    formIntroHeading: 'Save a new person',
    formIntroBlurb: 'Save the details of people that you regularly sail with.',
    buttonText: 'Save a person',
    buttonLink: 'people/save-person?source=people',
    buttonClass: 'govuk-button--start',
    buttonLocation: 'formIntro',
    reportType: 'people',
    reportTitles: ['Surname', 'Given name', 'Type'],
  },
  {
    urlStub: '/account',
    pageHeading: 'Account',
    pageBlurb: 'Manage your account details',
    buttonText: 'Edit details',
    buttonLink: '/account/edit',
    buttonLocation: 'intro',
  },
];

export default contentArray;
