export const nationalities = [
  { label: 'Afghan', value: 'AFG' },
  { label: 'Albanian', value: 'ALB' },
  { label: 'Algerian', value: 'DZA' },
  { label: 'American', value: 'USA' },
  { label: 'Andorran', value: 'AND' },
  { label: 'Angolan', value: 'AGO' },
  { label: 'Anguillan', value: 'AIA' },
  { label: 'Argentine', value: 'ARG' },
  { label: 'Armenian', value: 'ARM' },
  { label: 'Australian', value: 'AUS' },
  { label: 'Austrian', value: 'AUT' },
  { label: 'Azerbaijani', value: 'AZE' },
  { label: 'Bahamian', value: 'BHS' },
  { label: 'Bahraini', value: 'BHR' },
  { label: 'Bangladeshi', value: 'BGD' },
  { label: 'Barbadian', value: 'BRB' },
  { label: 'Belarusian', value: 'BLR' },
  { label: 'Belgian', value: 'BEL' },
  { label: 'Belizean', value: 'BLZ' },
  { label: 'Beninese', value: 'BEN' },
  { label: 'Bermudian', value: 'BMU' },
  { label: 'Bhutanese', value: 'BTN' },
  { label: 'Bolivian', value: 'BOL' },
  { label: 'Botswanan', value: 'BWA' },
  { label: 'Brazilian', value: 'BRA' },
  { label: 'British', value: 'GBR' },
  { label: 'British Virgin Islander', value: 'VGB' },
  { label: 'Bruneian', value: 'BRN' },
  { label: 'Bulgarian', value: 'BGR' },
  { label: 'Burkinan', value: 'BFA' },
  { label: 'Burmese', value: 'BUR' },
  { label: 'Burundian', value: 'BDI' },
  { label: 'Cambodian', value: 'KHM' },
  { label: 'Cameroonian', value: 'CMR' },
  { label: 'Canadian', value: 'CAN' },
  { label: 'Cape Verdean', value: 'CPV' },
  { label: 'Cayman Islander', value: 'CYM' },
  { label: 'Central African', value: 'CAF' },
  { label: 'Chadian', value: 'TCD' },
  { label: 'Chilean', value: 'CHL' },
  { label: 'Chinese', value: 'CHN' },
  { label: 'Citizen of Antigua and Barbuda', value: 'ATG' },
  { label: 'Citizen of Bosnia and Herzegovina', value: 'BIH' },
  { label: 'Citizen of Guinea-Bissau', value: 'GNB' },
  { label: 'Citizen of Kiribati', value: 'KIR' },
  { label: 'Citizen of Seychelles', value: 'SYC' },
  { label: 'Citizen of the Dominican Republic', value: 'DOM' },
  { label: 'Citizen of Vanuatu ', value: 'VUT' },
  { label: 'Colombian', value: 'COL' },
  { label: 'Comoran', value: 'COM' },
  { label: 'Congolese (Congo)', value: 'COG' },
  { label: 'Congolese (DRC)', value: 'COD' },
  { label: 'Cook Islander', value: 'COK' },
  { label: 'Costa Rican', value: 'CRI' },
  { label: 'Croatian', value: 'HRV' },
  { label: 'Cuban', value: 'CUB' },
  { label: 'Cymraes', value: 'GBR' },
  { label: 'Cymro', value: 'GBR' },
  { label: 'Cypriot', value: 'CYP' },
  { label: 'Czech', value: 'CZE' },
  { label: 'Danish', value: 'DNK' },
  { label: 'Djiboutian', value: 'DJI' },
  { label: 'Dominican', value: 'DMA' },
  { label: 'Dutch', value: 'NLD' },
  { label: 'East Timorese', value: 'TLS' },
  { label: 'Ecuadorean', value: 'ECU' },
  { label: 'Egyptian', value: 'EGY' },
  { label: 'Emirati', value: 'ARE' },
  { label: 'English', value: 'GBR' },
  { label: 'Equatorial Guinean', value: 'GNQ' },
  { label: 'Eritrean', value: 'ERI' },
  { label: 'Estonian', value: 'EST' },
  { label: 'Ethiopian', value: 'ETH' },
  { label: 'Faroese', value: 'FRO' },
  { label: 'Fijian', value: 'FJI' },
  { label: 'Filipino', value: 'PHL' },
  { label: 'Finnish', value: 'FIN' },
  { label: 'French', value: 'FRA' },
  { label: 'Gabonese', value: 'GAB' },
  { label: 'Gambian', value: 'GMB' },
  { label: 'Georgian', value: 'GEO' },
  { label: 'German', value: 'DEU' },
  { label: 'Ghanaian', value: 'GHA' },
  { label: 'Gibraltarian', value: 'GIB' },
  { label: 'Greek', value: 'GRC' },
  { label: 'Greenlandic', value: 'GRL' },
  { label: 'Grenadian', value: 'GRD' },
  { label: 'Guamanian', value: 'GUM' },
  { label: 'Guatemalan', value: 'GTM' },
  { label: 'Guinean', value: 'GIN' },
  { label: 'Guyanese', value: 'GUY' },
  { label: 'Haitian', value: 'HTI' },
  { label: 'Honduran', value: 'HND' },
  { label: 'Hong Konger', value: 'HKG' },
  { label: 'Hungarian', value: 'HUN' },
  { label: 'Icelandic', value: 'ISL' },
  { label: 'Indian', value: 'IND' },
  { label: 'Indonesian', value: 'IDN' },
  { label: 'Iranian', value: 'IRN' },
  { label: 'Iraqi', value: 'IRQ' },
  { label: 'Irish', value: 'IRL' },
  { label: 'Israeli', value: 'ISR' },
  { label: 'Italian', value: 'ITA' },
  { label: 'Ivorian', value: 'CIV' },
  { label: 'Jamaican', value: 'JAM' },
  { label: 'Japanese', value: 'JPN' },
  { label: 'Jordanian', value: 'JOR' },
  { label: 'Kazakh', value: 'KAZ' },
  { label: 'Kenyan', value: 'KEN' },
  { label: 'Kittitian', value: 'KNA' },
  { label: 'Kosovan', value: 'XKX' },
  { label: 'Kuwaiti', value: 'KWT' },
  { label: 'Kyrgyz', value: 'KGZ' },
  { label: 'Lao', value: 'LAO' },
  { label: 'Latvian', value: 'LVA' },
  { label: 'Lebanese', value: 'LBN' },
  { label: 'Liberian', value: 'LBR' },
  { label: 'Libyan', value: 'LBY' },
  { label: 'Liechtenstein citizen', value: 'LIE' },
  { label: 'Lithuanian', value: 'LTU' },
  { label: 'Luxembourger', value: 'LUX' },
  { label: 'Macanese', value: 'MAC' },
  { label: 'Macedonian', value: 'MKD' },
  { label: 'Malagasy', value: 'MDG' },
  { label: 'Malawian', value: 'MWI' },
  { label: 'Malaysian', value: 'MYS' },
  { label: 'Maldivian', value: 'MDV' },
  { label: 'Malian', value: 'MLI' },
  { label: 'Maltese', value: 'MLT' },
  { label: 'Marshallese', value: 'MHL' },
  { label: 'Martiniquais', value: 'MTQ' },
  { label: 'Mauritanian', value: 'MRT' },
  { label: 'Mauritian', value: 'MUS' },
  { label: 'Mexican', value: 'MEX' },
  { label: 'Micronesian', value: 'FSM' },
  { label: 'Moldovan', value: 'MDA' },
  { label: 'Monegasque', value: 'MCO' },
  { label: 'Mongolian', value: 'MNG' },
  { label: 'Montenegrin', value: 'MNE' },
  { label: 'Montserratian', value: 'MSR' },
  { label: 'Moroccan', value: 'MAR' },
  { label: 'Mosotho', value: 'LSO' },
  { label: 'Mozambican', value: 'MOZ' },
  { label: 'Namibian', value: 'NAM' },
  { label: 'Nauruan', value: 'NRU' },
  { label: 'Nepalese', value: 'NPL' },
  { label: 'New Zealander', value: 'NZL' },
  { label: 'Nicaraguan', value: 'NIC' },
  { label: 'Nigerian', value: 'NGA' },
  { label: 'Nigerien', value: 'NER' },
  { label: 'Niuean', value: 'NIU' },
  { label: 'North Korean', value: 'PRK' },
  { label: 'Northern Irish', value: 'GBR' },
  { label: 'Norwegian', value: 'NOR' },
  { label: 'Omani', value: 'OMN' },
  { label: 'Pakistani', value: 'PAK' },
  { label: 'Palauan', value: 'PLW' },
  { label: 'Palestinian', value: 'PSE' },
  { label: 'Panamanian', value: 'PAN' },
  { label: 'Papua New Guinean', value: 'PNG' },
  { label: 'Paraguayan', value: 'PRY' },
  { label: 'Peruvian', value: 'PER' },
  { label: 'Pitcairn Islander', value: 'PCN' },
  { label: 'Polish', value: 'POL' },
  { label: 'Portuguese', value: 'PRT' },
  { label: 'Prydeinig', value: 'GBR' },
  { label: 'Puerto Rican', value: 'PRI' },
  { label: 'Qatari', value: 'QAT' },
  { label: 'Romanian', value: 'ROU' },
  { label: 'Russian', value: 'RUS' },
  { label: 'Rwandan', value: 'RWA' },
  { label: 'Salvadorean', value: 'SLV' },
  { label: 'Sammarinese', value: 'SMR' },
  { label: 'Samoan', value: 'WSM' },
  { label: 'Sao Tomean', value: 'STP' },
  { label: 'Saudi Arabian', value: 'SAU' },
  { label: 'Scottish', value: 'GBR' },
  { label: 'Senegalese', value: 'SEN' },
  { label: 'Serbian', value: 'SRB' },
  { label: 'Sierra Leonean', value: 'SLE' },
  { label: 'Singaporean', value: 'SGP' },
  { label: 'Slovak', value: 'SVK' },
  { label: 'Slovenian', value: 'SVN' },
  { label: 'Solomon Islander', value: 'SLB' },
  { label: 'Somali', value: 'SOM' },
  { label: 'South African', value: 'ZAF' },
  { label: 'South Korean', value: 'KOR' },
  { label: 'South Sudanese', value: 'SSD' },
  { label: 'Spanish', value: 'ESP' },
  { label: 'Sri Lankan', value: 'LKA' },
  { label: 'St Helenian', value: 'SHN' },
  { label: 'St Lucian', value: 'LCA' },
  { label: 'Stateless', value: 'XXA' },
  { label: 'Sudanese', value: 'SDN' },
  { label: 'Surinamese', value: 'SUR' },
  { label: 'Swazi', value: 'SWZ' },
  { label: 'Swedish', value: 'SWE' },
  { label: 'Swiss', value: 'CHE' },
  { label: 'Syrian', value: 'SYR' },
  { label: 'Taiwanese', value: 'TWN' },
  { label: 'Tajik', value: 'TJK' },
  { label: 'Tanzanian', value: 'TZA' },
  { label: 'Thai', value: 'THA' },
  { label: 'Togolese', value: 'TGO' },
  { label: 'Tongan', value: 'TON' },
  { label: 'Trinidadian', value: 'TTO' },
  { label: 'Tristanian', value: 'SHN' },
  { label: 'Tunisian', value: 'TUN' },
  { label: 'Turkish', value: 'TUR' },
  { label: 'Turkmen', value: 'TKM' },
  { label: 'Turks and Caicos Islander', value: 'TCA' },
  { label: 'Tuvaluan', value: 'TUV' },
  { label: 'Ugandan', value: 'UGA' },
  { label: 'Ukrainian', value: 'UKR' },
  { label: 'Uruguayan', value: 'URY' },
  { label: 'Uzbek', value: 'UZB' },
  { label: 'Vatican citizen', value: 'VUT' },
  { label: 'Venezuelan', value: 'VEN' },
  { label: 'Vietnamese', value: 'VNM' },
  { label: 'Vincentian', value: 'VCT' },
  { label: 'Wallisian', value: 'WLF' },
  { label: 'Welsh', value: 'GBR' },
  { label: 'Yemeni', value: 'YEM' },
  { label: 'Zambian', value: 'ZMB' },
  { label: 'Zimbabwean', value: 'ZWE' },
];

/* Country data obtained from https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/1055492/FCDO-geographical-names-index-Feb22.csv/preview
   on 10/03/2021 */
export const countries = [
  { label: 'United Kingdom', value: 'GB' },
  { label: 'Afghanistan', value: 'AF' },
  { label: 'Albania', value: 'AL' },
  { label: 'Algeria', value: 'DZ' },
  { label: 'Andorra', value: 'AD' },
  { label: 'Angola', value: 'AO' },
  { label: 'Antigua and Barbuda', value: 'AG' },
  { label: 'Argentina', value: 'AR' },
  { label: 'Armenia', value: 'AM' },
  { label: 'Australia', value: 'AU' },
  { label: 'Austria', value: 'AT' },
  { label: 'Azerbaijan', value: 'AZ' },
  { label: 'Bahrain', value: 'BH' },
  { label: 'Bangladesh', value: 'BD' },
  { label: 'Barbados', value: 'BB' },
  { label: 'Belarus', value: 'BY' },
  { label: 'Belgium', value: 'BE' },
  { label: 'Belize', value: 'BZ' },
  { label: 'Benin', value: 'BJ' },
  { label: 'Bhutan', value: 'BT' },
  { label: 'Bolivia', value: 'BO' },
  { label: 'Bosnia and Herzegovina', value: 'BA' },
  { label: 'Botswana', value: 'BW' },
  { label: 'Brazil', value: 'BR' },
  { label: 'Brunei', value: 'BN' },
  { label: 'Bulgaria', value: 'BG' },
  { label: 'Burkina Faso', value: 'BF' },
  { label: 'Burundi', value: 'BI' },
  { label: 'Cambodia', value: 'KH' },
  { label: 'Cameroon', value: 'CM' },
  { label: 'Canada', value: 'CA' },
  { label: 'Cape Verde', value: 'CV' },
  { label: 'Central African Republic', value: 'CF' },
  { label: 'Chad', value: 'TD' },
  { label: 'Chile', value: 'CL' },
  { label: 'China', value: 'CN' },
  { label: 'Colombia', value: 'CO' },
  { label: 'Comoros', value: 'KM' },
  { label: 'Congo', value: 'CG' },
  { label: 'Congo (Democratic Republic)', value: 'CD' },
  { label: 'Costa Rica', value: 'CR' },
  { label: 'Croatia', value: 'HR' },
  { label: 'Cuba', value: 'CU' },
  { label: 'Cyprus', value: 'CY' },
  { label: 'Czechia', value: 'CZ' },
  { label: 'Denmark', value: 'DK' },
  { label: 'Djibouti', value: 'DJ' },
  { label: 'Dominica', value: 'DM' },
  { label: 'Dominican Republic', value: 'DO' },
  { label: 'East Timor', value: 'TL' },
  { label: 'Ecuador', value: 'EC' },
  { label: 'Egypt', value: 'EG' },
  { label: 'El Salvador', value: 'SV' },
  { label: 'Equatorial Guinea', value: 'GQ' },
  { label: 'Eritrea', value: 'ER' },
  { label: 'Estonia', value: 'EE' },
  { label: 'Eswatini', value: 'SZ' },
  { label: 'Ethiopia', value: 'ET' },
  { label: 'Fiji', value: 'FJ' },
  { label: 'Finland', value: 'FI' },
  { label: 'France', value: 'FR' },
  { label: 'Gabon', value: 'GA' },
  { label: 'Georgia', value: 'GE' },
  { label: 'Germany', value: 'DE' },
  { label: 'Ghana', value: 'GH' },
  { label: 'Greece', value: 'GR' },
  { label: 'Grenada', value: 'GD' },
  { label: 'Guatemala', value: 'GT' },
  { label: 'Guinea', value: 'GN' },
  { label: 'Guinea-Bissau', value: 'GW' },
  { label: 'Guyana', value: 'GY' },
  { label: 'Haiti', value: 'HT' },
  { label: 'Honduras', value: 'HN' },
  { label: 'Hungary', value: 'HU' },
  { label: 'Iceland', value: 'IS' },
  { label: 'India', value: 'IN' },
  { label: 'Indonesia', value: 'ID' },
  { label: 'Iran', value: 'IR' },
  { label: 'Iraq', value: 'IQ' },
  { label: 'Ireland', value: 'IE' },
  { label: 'Israel', value: 'IL' },
  { label: 'Italy', value: 'IT' },
  { label: 'Ivory Coast', value: 'CI' },
  { label: 'Jamaica', value: 'JM' },
  { label: 'Japan', value: 'JP' },
  { label: 'Jordan', value: 'JO' },
  { label: 'Kazakhstan', value: 'KZ' },
  { label: 'Kenya', value: 'KE' },
  { label: 'Kiribati', value: 'KI' },
  { label: 'Kosovo', value: 'XK' },
  { label: 'Kuwait', value: 'KW' },
  { label: 'Kyrgyzstan', value: 'KG' },
  { label: 'Laos', value: 'LA' },
  { label: 'Latvia', value: 'LV' },
  { label: 'Lebanon', value: 'LB' },
  { label: 'Lesotho', value: 'LS' },
  { label: 'Liberia', value: 'LR' },
  { label: 'Libya', value: 'LY' },
  { label: 'Liechtenstein', value: 'LI' },
  { label: 'Lithuania', value: 'LT' },
  { label: 'Luxembourg', value: 'LU' },
  { label: 'Madagascar', value: 'MG' },
  { label: 'Malawi', value: 'MW' },
  { label: 'Malaysia', value: 'MY' },
  { label: 'Maldives', value: 'MV' },
  { label: 'Mali', value: 'ML' },
  { label: 'Malta', value: 'MT' },
  { label: 'Marshall Islands', value: 'MH' },
  { label: 'Mauritania', value: 'MR' },
  { label: 'Mauritius', value: 'MU' },
  { label: 'Mexico', value: 'MX' },
  { label: 'Micronesia', value: 'FM' },
  { label: 'Moldova', value: 'MD' },
  { label: 'Monaco', value: 'MC' },
  { label: 'Mongolia', value: 'MN' },
  { label: 'Montenegro', value: 'ME' },
  { label: 'Morocco', value: 'MA' },
  { label: 'Mozambique', value: 'MZ' },
  { label: 'Myanmar (Burma)', value: 'MM' },
  { label: 'Namibia', value: 'NA' },
  { label: 'Nauru', value: 'NR' },
  { label: 'Nepal', value: 'NP' },
  { label: 'Netherlands', value: 'NL' },
  { label: 'New Zealand', value: 'NZ' },
  { label: 'Nicaragua', value: 'NI' },
  { label: 'Niger', value: 'NE' },
  { label: 'Nigeria', value: 'NG' },
  { label: 'North Korea', value: 'KP' },
  { label: 'North Macedonia', value: 'MK' },
  { label: 'Norway', value: 'NO' },
  { label: 'Oman', value: 'OM' },
  { label: 'Pakistan', value: 'PK' },
  { label: 'Palau', value: 'PW' },
  { label: 'Panama', value: 'PA' },
  { label: 'Papua New Guinea', value: 'PG' },
  { label: 'Paraguay', value: 'PY' },
  { label: 'Peru', value: 'PE' },
  { label: 'Philippines', value: 'PH' },
  { label: 'Poland', value: 'PL' },
  { label: 'Portugal', value: 'PT' },
  { label: 'Qatar', value: 'QA' },
  { label: 'Romania', value: 'RO' },
  { label: 'Russia', value: 'RU' },
  { label: 'Rwanda', value: 'RW' },
  { label: 'Samoa', value: 'WS' },
  { label: 'San Marino', value: 'SM' },
  { label: 'Sao Tome and Principe', value: 'ST' },
  { label: 'Saudi Arabia', value: 'SA' },
  { label: 'Senegal', value: 'SN' },
  { label: 'Serbia', value: 'RS' },
  { label: 'Seychelles', value: 'SC' },
  { label: 'Sierra Leone', value: 'SL' },
  { label: 'Singapore', value: 'SG' },
  { label: 'Slovakia', value: 'SK' },
  { label: 'Slovenia', value: 'SI' },
  { label: 'Solomon Islands', value: 'SB' },
  { label: 'Somalia', value: 'SO' },
  { label: 'South Africa', value: 'ZA' },
  { label: 'South Korea', value: 'KR' },
  { label: 'South Sudan', value: 'SS' },
  { label: 'Spain', value: 'ES' },
  { label: 'Sri Lanka', value: 'LK' },
  { label: 'St Kitts and Nevis', value: 'KN' },
  { label: 'St Lucia', value: 'LC' },
  { label: 'St Vincent', value: 'VC' },
  { label: 'Sudan', value: 'SD' },
  { label: 'Suriname', value: 'SR' },
  { label: 'Sweden', value: 'SE' },
  { label: 'Switzerland', value: 'CH' },
  { label: 'Syria', value: 'SY' },
  { label: 'Tajikistan', value: 'TJ' },
  { label: 'Tanzania', value: 'TZ' },
  { label: 'Thailand', value: 'TH' },
  { label: 'The Bahamas', value: 'BS' },
  { label: 'The Gambia', value: 'GM' },
  { label: 'Togo', value: 'TG' },
  { label: 'Tonga', value: 'TO' },
  { label: 'Trinidad and Tobago', value: 'TT' },
  { label: 'Tunisia', value: 'TN' },
  { label: 'Turkey', value: 'TR' },
  { label: 'Turkmenistan', value: 'TM' },
  { label: 'Tuvalu', value: 'TV' },
  { label: 'Uganda', value: 'UG' },
  { label: 'Ukraine', value: 'UA' },
  { label: 'United Arab Emirates', value: 'AE' },
  { label: 'United States', value: 'US' },
  { label: 'Uruguay', value: 'UY' },
  { label: 'Uzbekistan', value: 'UZ' },
  { label: 'Vanuatu', value: 'VU' },
  { label: 'Vatican City', value: 'VA' },
  { label: 'Venezuela', value: 'VE' },
  { label: 'Vietnam', value: 'VN' },
  { label: 'Yemen', value: 'YE' },
  { label: 'Zambia', value: 'ZM' },
  { label: 'Zimbabwe', value: 'ZW' },
];
